%YAML:1.0

# pre process
ds_size: 0.25
useful_corner_num: 30
stop_skip_enable: 0

# key points
plane_detection_thre: 0.01
plane_merge_normal_thre: 0.1
plane_merge_dis_thre: 0.3
voxel_size: 0.5
voxel_init_num: 10
proj_plane_num: 1
proj_image_resolution: 0.5
proj_image_high_inc: 0.1
proj_dis_min: 0.2
proj_dis_max: 5
summary_min_thre: 6
line_filter_enable: 1

# geo descriptor
descriptor_near_num: 15
descriptor_min_len: 2
descriptor_max_len: 300
max_constrait_dis: 2
similarity_threshold: 0.7
triangle_resolution: 2

# vis descriptor
vis_useful_corner_num: 30
vis_des_near_num: 50
vis_sim_threshold: 0.5

# candidate search
skip_near_num: 50
candidate_num: 5
sub_frame_num: 10
ransac_Rt_thr: 4
rough_dis_threshold: 1 #0.2 0.5
normal_threshold: 1
dis_threshold: 0.6
icp_threshold: 0.5  # plane-plane overlap, used for SLAM system

# result record
is_kitti: 0
